#!/usr/bin/python3
import sys
import subprocess
def print_result(request_num, results_file):
    for result in results_file:
        if result.startswith(f"{request_num[:-1]}="):
            print(result[:-1])
            return True
    return False
def get_data(command):
    # Specify the shell command you want to run
    shell_command = command
    # Run the command and capture the output
    result = subprocess.run(shell_command, shell=True, stdout=subprocess.PIPE, text=True)
    # Check if the command was successful
    if result.returncode == 0:
        # Access the output using result.stdout
        output = result.stdout
        return output
    else:
        print(f"Error: Command '{shell_command}' failed with return code {result.returncode}")
with open(sys.argv[1], "r") as request:
    with open("f_nums", "r") as f_nums:
        for line in request:
            if not print_result(line, f_nums):
                num = int(line[:-1])
                factor = int(get_data(f"factor {num}").split()[1])
                print(f"{num}={num // factor}*{factor}")



