#!/usr/bin/python3
import sys
import fnums
file_path = sys.argv[1]

with open(file_path, "r") as request:
        for request_num in request:
            request_num = int(request_num)
            for factor in fnums.factors:
                if not request_num % factor:
                    print(f"{request_num}={request_num // factor}*{factor}")
