#!/usr/bin/python3
import sys
import subprocess
def print_result(request_num, results_file):
    for result in results_file:
        if result.startswith(f"{request_num}="):
            print(result)
            return True
    return False
    # Specify the shell command you want to run
    shell_command = command
    # Run the command and capture the output
    result = subprocess.run(shell_command, shell=True, stdout=subprocess.PIPE, text=True)
    # Check if the command was successful
    if result.returncode == 0:
        # Access the output using result.stdout
        output = result.stdout
        return output
    else:
        print(f"Error: Command '{shell_command}' failed with return code {result.returncode}")

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)
file_path = sys.argv[1]

try:
    with open(file_path, "r") as request:
        with open("f_nums", "r") as f_nums:
            for request_num in request:
                if request_num[-1] == "\n":
                    request_num = request_num[:-1]
                if not print_result(request_num, f_nums):
                    print(f"{request_num}={request_num}*1")
except FileNotFoundError:
    print(f"File '{file_path}' not found.")
except ValueError:
    print("Invalid number in the file.")
